### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-constanza-sosa#1]
Really cool job @constanza-sosa  !!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] Move the font CSS before your main CSS
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Indent your styles and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-g/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto
- [x] Add a cool avatar to your GitHub profile page.

Let me know if you have any doubts ;)

Go for it!!

**Comment by constanza-sosa** [comment]
Done :)

**Comment by constanza-sosa** [comment]
@oneeyedman a descansar!!
